TT_STRING = 'STRING'
TT_INT = 'INT'
TT_FLOAT = 'FLOAT'
TT_PLUS = 'PLUS'
TT_MINUS = 'MINUS'
TT_MUL = 'MUL'
TT_DIV = 'DIV'
TT_POW = 'POWER'
TT_MOD = 'MODULO'
TT_LPAREN = 'LPAREN'
TT_RPAREN = 'RPAREN'
TT_LCURLY = 'LCURLY'
TT_RCURLY = 'RCURLY'
TT_LSQUARE = 'LSQUARE'
TT_RSQUARE = 'RSQUARE'
TT_IDENTIFIER = 'IDENTIFIER'
TT_KEYWORD = 'KEYWORD'
TT_EQUAL = 'EQUAL'
TT_DOUBLE_EQUAL = 'DOUBLE_EQUAL'
TT_NOT_EQUAL = 'NOT_EQUAL'
TT_LESS_THAN = 'LESS_THAN'
TT_LESS_THAN_EQUAL = 'LESS_THAN_EQUAL'
TT_GREATER_THAN = 'GREATER_THAN'
TT_GREATER_THAN_EQUAL = 'GREATER_THAN_EQUAL'
TT_COMMA = 'COMMA'
TT_ARROW = 'ARROW'
TT_NEWLINE = 'NEWLINE'
TT_EOF = 'EOF'
TT_INDEX = 'INDEX'


KEYWORD = [
	'var',
	'and',
	'or',
	'not',
	'if',
	'else if',
	'else',
	'do',
	'for',
	'to',
	'jump',
	'while',
	'fun',
	'return',
	'continue',
	'break'
]